name: Docker Build and Push
on:
  push:
    branches: ['*']
    tags: ['*']
jobs:
  build:
    name: Docker Image Build
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: unixgeek2/mysql-client
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Docker Hub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v5.1.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max